import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-payroll-tax-credit-recovery",
  "engine": "recovery",
  "title": "Payroll Tax Credit Recovery",
  "shortTitle": "Payroll Tax Credit Recovery",
  "tagline": "Identify payroll-based credits, calculate eligible wages, and reconcile amended filings and refunds.",
  "industry": "Employment Tax Recovery",
  "buyer": "Employers and payroll providers",
  "uiPort": 4687,
  "apiPort": 5687,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Payroll Tax Credit Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds in one accountable workflow. Identify payroll-based credits, calculate eligible wages, and reconcile amended filings and refunds.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Payroll Tax Credit Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("employer-location-registry","PTC01","Employer location registry","Execute employer location registry using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed employer location registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Employer location registry Reference","text","PTC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("employee-wage-ingestion","PTC02","Employee wage ingestion","Execute employee wage ingestion using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed employee wage ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Employee wage ingestion Reference","text","PTC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("eligibility-population-matching","PTC03","Eligibility population matching","Execute eligibility population matching using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed eligibility population matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Eligibility population matching Reference","text","PTC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("certification-deadline-control","PTC04","Certification deadline control","Execute certification deadline control using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed certification deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Certification deadline control Reference","text","PTC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("qualified-wage-calculation","PTC05","Qualified wage calculation","Execute qualified wage calculation using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed qualified wage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Qualified wage calculation Reference","text","PTC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("credit-interaction-rules","PTC06","Credit interaction rules","Execute credit interaction rules using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed credit interaction rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Credit interaction rules Reference","text","PTC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("federal-credit-calculation","PTC07","Federal credit calculation","Execute federal credit calculation using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed federal credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Federal credit calculation Reference","text","PTC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("state-credit-calculation","PTC08","State credit calculation","Execute state credit calculation using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed state credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","State credit calculation Reference","text","PTC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("payroll-deposit-reconciliation","PTC09","Payroll deposit reconciliation","Execute payroll deposit reconciliation using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed payroll deposit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Payroll deposit reconciliation Reference","text","PTC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("form-amendment-preparation","PTC10","Form amendment preparation","Execute form amendment preparation using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed form amendment preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Form amendment preparation Reference","text","PTC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("supporting-document-package","PTC11","Supporting document package","Execute supporting document package using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed supporting document package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Supporting document package Reference","text","PTC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("tax-notice-workflow","PTC12","Tax notice workflow","Execute tax notice workflow using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed tax notice workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Tax notice workflow Reference","text","PTC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("refund-tracking","PTC13","Refund tracking","Execute refund tracking using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed refund tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Refund tracking Reference","text","PTC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("general-ledger-reconciliation","PTC14","General-ledger reconciliation","Execute general-ledger reconciliation using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed general-ledger reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","General-ledger reconciliation Reference","text","PTC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]}),
feature("program-location-analytics","PTC15","Program location analytics","Execute program location analytics using employee wages, work locations, tax deposits, qualified populations, state and federal credits, amendments, notices, and refunds.","Produce a governed program location analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Payroll Period","text","Employer / Payroll Period · Standard Case"],["caseReference","Program location analytics Reference","text","PTC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1112500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1346125],["domainDriver","Credit Program","select","Work Opportunity",["Work Opportunity","Paid leave","State hiring credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Employer location registry case","Employee wage ingestion case","Eligibility population matching case","Certification deadline control case","Qualified wage calculation case"]})
]);
